# 80-rootfs-ifnames.sh — kernel-style NIC names (eth0 / wlan0) via systemd .link.
#
# WHAT:  drops two systemd .link files that rename the carrier NICs by driver — the wired
#        Realtek r8168 -> eth0, the RTL8852BU WiFi -> wlan0.
# WHY:   the Unitree stack hard-codes `eth0` twice (video_hub's cyclonedds.xml DDS iface + its
#        baked-in `udpsink ... multicast-iface=eth0`), and 40-rootfs-static-ip binds the keyfile to
#        eth0. Without this the 7.2 image uses systemd predictable names (enP8p1s0 / wlxXXXX), the
#        static-IP keyfile never matches, and the board comes up with no LAN IP.
# WHY .link (not net.ifnames=0): the initrd flow regenerates /boot/extlinux/extlinux.conf from a
#        BSP template at flash time, so a build-time edit to the rootfs cmdline is discarded
#        (verified on a 7.2 flash — the arg never reached /proc/cmdline). A rootfs .link is not
#        regenerated by flash and renames deterministically by driver. Confirmed live: eth0 comes
#        up with the static IP and wlan0 renames correctly.
# SKIP:  5.1.6 already boots net.ifnames=0 (NIC is eth0), so it doesn't include this patch.
#
# Sourced by apply_patches() with $LFT $SUDO + log/ok in scope.

_nd="$LFT/rootfs/etc/systemd/network"
$SUDO mkdir -p "$_nd"

log "installing NIC-rename .link files (r8168 -> eth0, rtl8852bu -> wlan0)"
$SUDO tee "$_nd/10-eth0.link" >/dev/null <<'EOF'
# Unitree G1 carrier: name the wired Realtek NIC eth0 (the Unitree stack expects eth0).
[Match]
Driver=r8168

[Link]
Name=eth0
EOF
$SUDO tee "$_nd/11-wlan0.link" >/dev/null <<'EOF'
# Unitree G1 carrier: name the RTL8852BU WiFi wlan0.
[Match]
Driver=rtl8852bu

[Link]
Name=wlan0
EOF
ok "eth0/wlan0 .link files installed"
